### ISSUE TITLE
Disable memory cache for fallbackImage & fallbackAssetImage

### ISSUE THREAD

**Issue by mchome** [mchome/flutter_advanced_networkimage#67]
The fallback image should not be cached in flutter's `ImageCache` singleton.

**Comment by mchome** [comment]
It's hard to determining the fallback was used before pushing `ImageStreamCompleter` to `ImageCache`.
So `disableMemoryCache` + `useDiskCache` is just a temporary solution.

**Comment by davbaron** [comment]
OK...I will try to use that for now.  However, when I tried to use the new option (disableMemoryCache) it does not show up as an option in VS Code.  I have tried:

flutter packages get
flutter packages upgrade
flutter update-packages
flutter update-packages --force-upgrade

I have also tried shutting dow VS Code and restarting it...  however nothing seems to 'pull in' the latest version.  I can see the new code in git, so i know it's there...

Thank you again...

**Comment by mchome** [comment]
Sorry, i haven't put it into dart pub yet, because i want to know more details about https://github.com/mchome/flutter_advanced_networkimage/issues/68.
You can try git version by this:
```yaml
dependencies:
  flutter_advanced_networkimage:
    git:
      url: git://github.com/mchome/flutter_advanced_networkimage.git
      ref: fc36d88e80fc2a5628c0a69c19930535d1385cd1
```
